- name: Run Hello World
  ansible.windows.win_powershell:
    script: |
      echo "hello world"
  remote_user: remoteuser
  tags:
    - maintenance
    - run_hello_world

- name: Determine Hostname
  ansible.windows.win_powershell:
    script: |
      $env:computername
  remote_user: remoteuser
  tags:
    - maintenance
    - determine_hostname

- name: Get Disk Space
  ansible.windows.win_powershell:
    script: |
      Get-PSDrive C; Get-PSDrive D
  register: disk_space
  tags:
    - maintenance
    - get_disk_space

- name: Report Disk Space
  debug:
    var: disk_space.output
  tags:
    - maintenance
    - report_disk_space