- name: Run Hello World
  ansible.windows.win_powershell:
    script: |
      echo "hello world"
  remote_user: remoteuser
  tags:
    - maintenance
    - run_hello_world

- name: Clean Up C Drive
  ansible.windows.win_powershell:
    script: |
      Get-ChildItem -Path "C:\Users\julia\Downloads\TestRemoval" -Recurse -Depth 0 |
      Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-0) } |
      Remove-Item -WhatIf -Force -Recurse
  remote_user: remoteuser
  tags:
    - maintenance
    - clean_up_c_drive

- name: Get Disk Space
  ansible.windows.win_powershell:
    script: |
      Get-PSDrive C; Get-PSDrive D
  register: disk_space
  tags:
    - maintenance
    - get_disk_space

- name: Report Disk Space
  debug:
    var: disk_space.output
  tags:
    - maintenance
    - report_disk_space